# Generated by Django 5.2.7 on 2025-11-01 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing__type_listing_description_listing_sold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
