# Generated by Django 5.2.7 on 2025-11-01 19:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename__type_listing_type_alter_listing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('AR', 'Alternative Rock'), ('HR', 'Hard Rock'), ('CR', 'Classic Rock'), ('MT', 'Metal'), ('PR', 'Punk Rock'), ('IR', 'Indie Rock'), ('POP', 'Pop'), ('SP', 'Synth Pop'), ('EL', 'Electronic'), ('HO', 'House'), ('TC', 'Techno'), ('EDM', 'EDM (Electronic Dance Music)'), ('HH', 'Hip Hop'), ('RAP', 'Rap'), ('RNB', 'R&B / Soul'), ('TR', 'Trap'), ('JZ', 'Jazz'), ('BL', 'Blues'), ('SO', 'Soul'), ('FK', 'Funk'), ('CO', 'Country'), ('RG', 'Reggae'), ('LA', 'Latin'), ('FO', 'Folk'), ('GP', 'Gospel'), ('AF', 'Afrobeat'), ('WO', 'World Music'), ('CL', 'Classical'), ('KP', 'K-Pop')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('RC', 'Records (Vinyles, CD, Cassettes)'), ('DA', 'Digital Album'), ('SG', 'Single'), ('LA', 'Live Album'), ('CP', 'Compilation'), ('CT', 'Clothing (T-Shirts, Hoodies, etc.)'), ('HT', 'Hats / Caps'), ('SH', 'Shoes'), ('AC', 'Accessories (Bracelets, Chains, etc.)'), ('BG', 'Bags / Backpacks'), ('PT', 'Posters'), ('ST', 'Stickers'), ('AW', 'Artwork / Paintings'), ('PH', 'Photography Prints'), ('IN', 'Musical Instrument'), ('EQ', 'Studio / Audio Equipment'), ('SM', 'Sheet Music / Tabs'), ('LE', 'Limited Edition Item'), ('CL', 'Collectible Item'), ('GF', 'Gift Item / Merch Box'), ('TK', 'Concert Tickets'), ('MS', 'Miscellaneous')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
