# Generated by Django 5.2.7 on 2025-11-02 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_band_like_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('theme-ocean', 'Ocean'), ('theme-dark', 'Dark'), ('theme-mint', 'Mint'), ('theme-sand', 'Sand'), ('theme-glacier', 'Glacier'), ('theme-fire', 'Fire'), ('theme-pink', 'Pink'), ('theme-violet', 'Violet'), ('theme-amber', 'Amber'), ('theme-cyan', 'Cyan'), ('theme-lime', 'Lime'), ('theme-coral', 'Coral'), ('theme-teal', 'Teal'), ('theme-indigo', 'Indigo'), ('theme-rose', 'Rose')], default='theme-ocean', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.band'),
        ),
    ]
