# Generated by Django 5.2.7 on 2025-11-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_setting_alter_listing_band'),
    ]

    operations = [
        migrations.DeleteModel(
            name='setting',
        ),
    ]
